### ISSUE TITLE
Options aren't positioned correctly (Checkboxes, inputs, etc.)

### ISSUE THREAD

**Issue by rotntake** [argon-rbx/argon-roblox#2]
![image](https://github.com/argon-rbx/argon-roblox/assets/126120456/cdd065ca-3e09-4a96-9d4d-93503d8d1eb7)
My screen's resolution is 1920x1080.

**Comment by DervexDev** [comment]
Options are positioned just fine. Plugin widgets are sometimes laggy for a short period of time after they are created. Is this bug permanent for you? I hope not because there is nothing I can do about it. Also I didn't face this issue on any OS or machine.

**Comment by rotntake** [comment]
It seems permanent, even if i scale it or move it around. It just stays like that.

**Comment by DervexDev** [comment]
Oh I think I know where the problem is. Make sure you have this beta feature enabled:
<img width="484" alt="image" src="https://github.com/argon-rbx/argon-roblox/assets/78505208/a19b2498-12e8-4a71-ada0-65407a0944f8">

Hopefully Roblox will release this feature before the release of Argon otherwise I will have to leave a note somewhere.

**Comment by rotntake** [comment]
Fixes the issue.
