### ISSUE TITLE
"Unavailable during playtest" window seems unnecessary

### ISSUE THREAD

**Issue by jmmk** [argon-rbx/argon-roblox#4]
I might be misunderstanding something, or maybe I don't have a good workflow, but every time I run the game to test changes I see this popup:

<img width="296" alt="image" src="https://github.com/argon-rbx/argon-roblox/assets/1122242/d384741c-3f57-4179-a462-77e1007368d6">

It might be good to have a way to disable it or only show it once.

**Comment by DervexDev** [comment]
Thanks for the report but this is actually a Roblox Studio bug, see this [video](https://devforum.roblox.com/t/argon-full-featured-tool-for-roblox-development/2021776/809?u=dervex). Only way to get around this issue is to disable user plugins in test mode as described [here](https://devforum.roblox.com/t/argon-full-featured-tool-for-roblox-development/2021776/811?u=dervex).
